export const PLAYER_ANIM_SIZE_MULTIPLIER = 4.4;
export const PLAYER_STATIC_SIZE_MULTIPLIER = 3.4;

export const PROJECTILE_SPRITE_SIZE_MULTIPLIER = 5.2;
export const PROJECTILE_MIN_SPRITE_SIZE = 28;

export const CROSS_PROJECTILE_SPRITE_SIZE_MULTIPLIER = 5.8;
export const CROSS_PROJECTILE_MIN_SPRITE_SIZE = 32;

export const WHIP_SLASH_SIZE_MULTIPLIER = 1.7;

