export const WEAPON_DEFS = {
  bouncing_slipper: {
    id: 'bouncing_slipper',
    name: '弹跳拖鞋',
    nameEn: 'Bouncing Slipper',
    type: 'ranged',
    behavior: 'bounce',
    baseDamage: 14,
    baseFireRate: 900,
    baseRange: 360,
    baseCount: 1,
    basePierce: 1,
    maxLevel: 8,
    tags: ['ricochet'],
    levelDesc: ['投出会弹跳的家族拖鞋', '数量+1', '伤害+30%', '冷却-15%', '弹跳+1', '伤害+30%', '范围+25%', '数量+1，弹跳+1'],
    flavor: '据说它会自己找到欠账的人。'
  },
  spinning_ladle: {
    id: 'spinning_ladle',
    name: '旋转汤勺',
    nameEn: 'Spinning Ladle',
    type: 'orbit',
    behavior: 'orbit',
    baseDamage: 10,
    baseFireRate: 0,
    baseRange: 92,
    baseCount: 1,
    maxLevel: 8,
    tags: ['orbit'],
    levelDesc: ['环绕玩家旋转', '数量+1', '伤害+30%', '半径+15%', '数量+1', '伤害+30%', '旋转速度+25%', '数量+1'],
    flavor: '锅里没有汤，只有审判。'
  },
  boomerang_cleaver: {
    id: 'boomerang_cleaver',
    name: '回旋菜刀',
    nameEn: 'Boomerang Cleaver',
    type: 'ranged',
    behavior: 'boomerang',
    baseDamage: 18,
    baseFireRate: 1300,
    baseRange: 320,
    baseCount: 1,
    basePierce: 2,
    maxLevel: 8,
    tags: ['ricochet', 'heavy'],
    levelDesc: ['飞出后折返', '数量+1', '伤害+30%', '冷却-15%', '穿透+1', '伤害+30%', '距离+25%', '数量+1'],
    flavor: 'Gennaro 坚称这是餐具。'
  },
  throwing_chopsticks: {
    id: 'throwing_chopsticks',
    name: '投掷筷子',
    nameEn: 'Throwing Chopsticks',
    type: 'ranged',
    behavior: 'needle',
    baseDamage: 11,
    baseFireRate: 520,
    baseRange: 420,
    baseCount: 1,
    basePierce: 1,
    maxLevel: 8,
    tags: ['ricochet'],
    levelDesc: ['朝最近敌人穿刺', '数量+1', '伤害+30%', '冷却-15%', '穿透+1', '伤害+30%', '速度+25%', '数量+1'],
    flavor: '一双找不到饭碗的筷子。'
  },
  holy_toast: {
    id: 'holy_toast',
    name: '神圣吐司',
    nameEn: 'Holy Toast',
    type: 'lob',
    behavior: 'lob',
    baseDamage: 22,
    baseFireRate: 1500,
    baseRange: 300,
    baseCount: 1,
    maxLevel: 8,
    tags: ['heavy'],
    levelDesc: ['抛物线落地溅射', '范围+20%', '伤害+30%', '冷却-15%', '数量+1', '伤害+30%', '溅射+25%', '数量+1'],
    flavor: '烤焦边缘像圣光一样发黑。'
  },
  garlic_breath: {
    id: 'garlic_breath',
    name: '大蒜气息',
    nameEn: 'Garlic Breath',
    type: 'aura',
    behavior: 'aura',
    baseDamage: 4,
    baseFireRate: 420,
    baseRange: 70,
    baseCount: 1,
    maxLevel: 8,
    tags: ['hot', 'orbit'],
    levelDesc: ['持续伤害光环', '范围+20%', '伤害+30%', '冷却-15%', '范围+20%', '伤害+30%', '击退+15%', '范围+25%'],
    flavor: '餐桌社交的终极防御。'
  },
  rolling_pin: {
    id: 'rolling_pin',
    name: '擀面杖',
    nameEn: 'Rolling Pin',
    type: 'melee',
    behavior: 'sweep',
    baseDamage: 16,
    baseFireRate: 720,
    baseRange: 86,
    baseArc: Math.PI / 2.6,
    baseCount: 1,
    maxLevel: 8,
    tags: ['heavy'],
    levelDesc: ['近身横扫', '范围+20%', '伤害+30%', '冷却-15%', '反向横扫', '伤害+30%', '弧度+20%', '二连横扫'],
    flavor: '家族会议通常由它主持。'
  },
  hot_sauce_bottle: {
    id: 'hot_sauce_bottle',
    name: '辣酱瓶',
    nameEn: 'Hot Sauce Bottle',
    type: 'spray',
    behavior: 'spray',
    baseDamage: 8,
    baseFireRate: 1800,
    baseRange: 240,
    baseCount: 1,
    basePierce: 0,
    maxLevel: 8,
    tags: ['hot'],
    levelDesc: ['扇形喷射辣酱', '喷射+1', '伤害+30%', '冷却-15%', '地面灼烧延长', '伤害+30%', '范围+25%', '喷射+1'],
    flavor: '标签写着温和。标签在说谎。'
  },
  thermal_bag: {
    id: 'thermal_bag',
    name: '保温袋',
    nameEn: 'Thermal Bag',
    type: 'functional',
    behavior: 'shield',
    functional: true,
    baseFireRate: 8000,
    maxLevel: 8,
    tags: ['shield'],
    levelDesc: ['周期性获得 1 层护盾', '充能稍快', '护盾韧性提升', '最多 2 层', '充能稍快', '护盾韧性提升', '充能更快', '最多 3 层'],
    flavor: '保护外卖，也保护你。'
  },
  freezer_gate: {
    id: 'freezer_gate',
    name: '冷柜门',
    nameEn: 'Freezer Gate',
    type: 'functional',
    behavior: 'freeze',
    functional: true,
    baseFireRate: 6200,
    maxLevel: 8,
    tags: ['freeze'],
    levelDesc: ['发射一道冻结射线', '冻结更久', '扫射更快', '射线 +1', '冻结更久', '扫射更快', '冻结更久', '射线 +1'],
    flavor: '后厨里最不讲道理的一扇门。'
  },
  service_bell: {
    id: 'service_bell',
    name: '服务铃',
    nameEn: 'Service Bell',
    type: 'functional',
    behavior: 'clear',
    functional: true,
    baseFireRate: 90000,
    maxLevel: 8,
    tags: ['clear'],
    levelDesc: ['周期性清理普通敌人和掉落物', '冷却缩短', '冷却缩短', '冷却缩短', '冷却缩短', '保留掉落物', '冷却缩短', '冷却降至 45 秒'],
    flavor: '叮。现在轮到怪物排队。'
  },
  whip: {
    id: 'whip',
    name: '鞭子',
    nameEn: 'Whip',
    type: 'melee',
    behavior: 'sweep',
    hidden: true,
    baseDamage: 15,
    baseFireRate: 600,
    baseRange: 80,
    baseArc: Math.PI / 3,
    maxLevel: 8,
    tags: ['heavy'],
    levelDesc: ['隐藏彩蛋武器', '范围+20%', '伤害+30%', '冷却-15%', '反向斩击', '伤害+30%', '范围+20%', '二连斩击'],
    flavor: '不该出现在厨房里的经典遗物。'
  },
  cross: {
    id: 'cross',
    name: '十字架',
    nameEn: 'Cross',
    type: 'ranged',
    behavior: 'boomerang',
    hidden: true,
    baseDamage: 12,
    baseFireRate: 1200,
    baseRange: 300,
    baseCount: 1,
    maxLevel: 8,
    tags: ['ricochet'],
    levelDesc: ['隐藏彩蛋武器', '数量+1', '飞行距离+30%', '伤害+25%', '数量+1，穿透+1', '伤害+30%', '冷却-15%', '数量+1'],
    flavor: '适合驱逐账单，也适合驱逐别的东西。'
  }
};

export const EVOLUTION_DEFS = {
  divine_slipper: {
    id: 'divine_slipper',
    name: '神圣拖鞋',
    nameEn: 'Divine Slipper',
    baseWeaponId: 'bouncing_slipper',
    requiredPassiveId: 'running_shoes',
    baseDamageMultiplier: 1.8,
    behavior: 'bounce',
    flavor: '它终于学会了带着神圣怒气回家。'
  },
  excalibur_ladle: {
    id: 'excalibur_ladle',
    name: '圣剑汤勺',
    nameEn: 'Excalibur Ladle',
    baseWeaponId: 'spinning_ladle',
    requiredPassiveId: 'bubble_foam',
    baseDamageMultiplier: 1.7,
    behavior: 'orbit',
    flavor: '每一次搅拌都像拔剑。'
  },
  meat_grinder: {
    id: 'meat_grinder',
    name: '绞肉机',
    nameEn: 'Meat Grinder',
    baseWeaponId: 'boomerang_cleaver',
    requiredPassiveId: 'fitness_bracer',
    baseDamageMultiplier: 2.0,
    behavior: 'boomerang',
    flavor: '它不问肉从哪里来。'
  },
  infinite_hot_pot: {
    id: 'infinite_hot_pot',
    name: '无限火锅',
    nameEn: 'Infinite Hot Pot',
    baseWeaponId: 'hot_sauce_bottle',
    requiredPassiveId: 'magnifying_glass',
    baseDamageMultiplier: 1.9,
    behavior: 'spray',
    flavor: '锅底永远不见底。'
  },
  michelin_cloak: {
    id: 'michelin_cloak',
    name: '米其林披风',
    nameEn: 'Michelin Cloak',
    baseWeaponId: 'thermal_bag',
    requiredPassiveId: 'takeout_lid',
    baseDamageMultiplier: 1,
    behavior: 'shield',
    functional: true,
    flavor: '满层护盾会反弹接触伤害，并在濒死时替你挡一次。'
  },
  infinite_buffet: {
    id: 'infinite_buffet',
    name: '无限自助餐',
    nameEn: 'Infinite Buffet',
    baseWeaponId: 'freezer_gate',
    requiredPassiveId: 'empty_boba_cup',
    baseDamageMultiplier: 1,
    behavior: 'freeze',
    functional: true,
    flavor: '冻结扫射还会削去敌人当前生命。'
  },
  gorgeous_moonboba: {
    id: 'gorgeous_moonboba',
    name: '华丽月亮珍珠',
    nameEn: 'Gorgeous Moonboba',
    baseWeaponId: 'service_bell',
    requiredPassiveId: 'family_recipe',
    baseDamageMultiplier: 1,
    behavior: 'clear',
    functional: true,
    flavor: '清屏、牵引经验糖，并洒下月光弹幕。'
  }
};
